export const latestList = [
  {
    id: 0,
    title: 'Transfer to',
    name: 'Muhammad UFO',
    desc: 'Personal Payment',
    img: 'https://avatars.githubusercontent.com/u/90573543?v=4',
    price: '-$35.00',
    dec: true,
  },
  {
    id: 1,
    title: 'FC Bayern Munich',
    name: '',
    desc: 'Shopping',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png',
    price: '-$128.00',
    dec: true,
  },
  {
    id: 2,
    title: 'Chelsea',
    name: '',
    desc: 'Communication',
    img: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png',
    price: '-$10.00',
    dec: true,
  },
  {
    id: 3,
    title: 'Real Madrid',
    name: '',
    desc: 'Personal Payment',
    img: 'https://w7.pngwing.com/pngs/402/224/png-transparent-history-of-real-madrid-c-f-la-liga-football-football-emblem-logo-sticker.png',
    price: '+$300.58',
    dec: false,
  },
  {
    id: 4,
    title: 'Manchester United',
    name: '',
    desc: 'Personal Payment',
    img: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png',
    price: '-$35.00',
    dec: true,
  },
]
